#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
export UNION_PRELOAD="${HERE}"
export LD_PRELOAD="${HERE}/libunionpreload.so"
export PATH="${HERE}"/usr:"${HERE}"/usr/libexec:"${HERE}"/usr/bin:"${HERE}"/usr/lib:"${HERE}"/usr/include:"${HERE}"/usr/var:"${HERE}"/usr/var/run:"${HERE}"/usr/share:"${HERE}"/usr/share/doc:"${HERE}"/usr/share/qemu:"${HERE}"/usr/share/qemu/keymaps:"${HERE}"/usr/share/qemu/firmware:"${HERE}"/usr/share/applications:"${HERE}"/usr/share/mime:"${HERE}"/usr/share/mime/x-epoc:"${HERE}"/usr/share/mime/inode:"${HERE}"/usr/share/mime/video:"${HERE}"/usr/share/mime/text:"${HERE}"/usr/share/mime/application:"${HERE}"/usr/share/mime/audio:"${HERE}"/usr/share/mime/model:"${HERE}"/usr/share/mime/image:"${HERE}"/usr/share/mime/font:"${HERE}"/usr/share/mime/x-content:"${HERE}"/usr/share/mime/packages:"${HERE}"/usr/share/mime/multipart:"${HERE}"/usr/share/mime/message:"${PATH}"
export LD_LIBRARY_PATH="${HERE}"/usr:"${HERE}"/usr/libexec:"${HERE}"/usr/bin:"${HERE}"/usr/lib:"${HERE}"/usr/include:"${HERE}"/usr/var:"${HERE}"/usr/var/run:"${HERE}"/usr/share:"${HERE}"/usr/share/doc:"${HERE}"/usr/share/qemu:"${HERE}"/usr/share/qemu/keymaps:"${HERE}"/usr/share/qemu/firmware:"${HERE}"/usr/share/applications:"${HERE}"/usr/share/mime:"${HERE}"/usr/share/mime/x-epoc:"${HERE}"/usr/share/mime/inode:"${HERE}"/usr/share/mime/video:"${HERE}"/usr/share/mime/text:"${HERE}"/usr/share/mime/application:"${HERE}"/usr/share/mime/audio:"${HERE}"/usr/share/mime/model:"${HERE}"/usr/share/mime/image:"${HERE}"/usr/share/mime/font:"${HERE}"/usr/share/mime/x-content:"${HERE}"/usr/share/mime/packages:"${HERE}"/usr/share/mime/multipart:"${HERE}"/usr/share/mime/message:"${LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="${HERE}"/usr:"${HERE}"/usr/libexec:"${HERE}"/usr/bin:"${HERE}"/usr/lib:"${HERE}"/usr/include:"${HERE}"/usr/var:"${HERE}"/usr/var/run:"${HERE}"/usr/share:"${HERE}"/usr/share/doc:"${HERE}"/usr/share/qemu:"${HERE}"/usr/share/qemu/keymaps:"${HERE}"/usr/share/qemu/firmware:"${HERE}"/usr/share/applications:"${HERE}"/usr/share/mime:"${HERE}"/usr/share/mime/x-epoc:"${HERE}"/usr/share/mime/inode:"${HERE}"/usr/share/mime/video:"${HERE}"/usr/share/mime/text:"${HERE}"/usr/share/mime/application:"${HERE}"/usr/share/mime/audio:"${HERE}"/usr/share/mime/model:"${HERE}"/usr/share/mime/image:"${HERE}"/usr/share/mime/font:"${HERE}"/usr/share/mime/x-content:"${HERE}"/usr/share/mime/packages:"${HERE}"/usr/share/mime/multipart:"${HERE}"/usr/share/mime/message:"${XDG_DATA_DIRS}"
export GSETTINGS_SCHEMA_DIR="${HERE}"/usr/share/glib-2.0/schemas/:"${GSETTINGS_SCHEMA_DIR}"
if [ -z "${1}" ]; then
	exec q
elif [[ "${1}" =~ ^(qemu-edid|qemu-system-tricore|qemu-system-aarch64|qemu-io|qemu-keymap|qemu-ga|qemu-nbd|qemu-storage-daemon|qemu-aarch64_be|qemu-img|qemu-system-i386|qemu-armeb|qemu-system-arm|qemu-x86_64|qemu-alpha|qemu-loongarch64|qemu-i386|qemu-aarch64|qemu-arm|qemu-system-loongarch64|elf2dmp|qemu-sh4eb|qemu-pr-helper|qemu-system-x86_64|qemu-bridge-helper|virtfs-proxy-helper|q|quickemu|quickget|macrecovery|gum)$ ]]; then
	args=( "${@}" )
	args[0]="${1}"
	set "${args[@]}"
exec "${@}"
fi
